/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:83ecbe91-3275-4fd9-8aab-91d9cbe7f95a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qkK41FSaG",
    "aws_user_pools_web_client_id": "47j4sb9q0vmv2veo6t9elrot7e",
    "oauth": {}
};


export default awsmobile;
